# This file was generated by GoReleaser. DO NOT EDIT.
cask "synqcli" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "46ed4ef15989e7d8d89a111e33ff0ef80f65ce0999162aa6d55743511415c552"
      url "https://github.com/getsynq/synqcli/releases/download/v#{version}/synqcli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e32debf2c155431568673c88ce9efd95a92bcf9828932eeeaa7d0538cdf3fcf7"
      url "https://github.com/getsynq/synqcli/releases/download/v#{version}/synqcli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b5576196d6bdd908429107aed967fcd3aaca15778a6f60dc4c6de65f325f9b3d"
      url "https://github.com/getsynq/synqcli/releases/download/v#{version}/synqcli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3a5f9ed243a9c73479b00181f31868ae24b414194aa214041ed7f039e7a2603a"
      url "https://github.com/getsynq/synqcli/releases/download/v#{version}/synqcli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "synqcli"
  desc "Declare Coalesce Quality monitors, SQL tests and deployment rules as code"
  homepage "https://docs.synq.io/monitors/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synqcli"
  bash_completion "completions/synqcli.bash"
  zsh_completion "completions/_synqcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/synqcli"]
    end
  end

  # No zap stanza required
end
