# This file was generated by GoReleaser. DO NOT EDIT.
cask "synqcli" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "ee2f15f10e31bccce36f58faa357dbc0678a6eef53070356fbc91ef54cb8535d"
      url "https://github.com/getsynq/synqcli/releases/download/v#{version}/synqcli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "22bafba3d7287992df45abac4c45e6bee46e04768cbb89a47dced5df230e2794"
      url "https://github.com/getsynq/synqcli/releases/download/v#{version}/synqcli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d5530de4edcf6643b8b7bb837402baf00298c4f2a633f13bfb5794a0790960f1"
      url "https://github.com/getsynq/synqcli/releases/download/v#{version}/synqcli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bc3f50961dea088e90d5ce216df5bdb95dd5e690bd566eb9882502064e36f33c"
      url "https://github.com/getsynq/synqcli/releases/download/v#{version}/synqcli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "synqcli"
  desc "Declare Coalesce Quality monitors, SQL tests and deployment rules as code"
  homepage "https://docs.synq.io/monitors/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synqcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/synqcli"]
    end
  end

  # No zap stanza required

end
