# This file was generated by dev-helpers/publish-homebrew-cask.sh. DO NOT EDIT.
cask "synq-recon" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "a98015979f2352ef592244a571378bcfa48bc581c52badc63b3c965dd2f4e037"
      url "https://github.com/getsynq/synq-recon/releases/download/v#{version}/synq-recon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b3660376ad35aac40ab41b47c3f18345d630363d8d0b66f9aba0f26f3e7ad7cb"
      url "https://github.com/getsynq/synq-recon/releases/download/v#{version}/synq-recon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "11e6fffacc375faa80635c6f9044538c9ce5cbe0f4eca640204d0134c7054b64"
      url "https://github.com/getsynq/synq-recon/releases/download/v#{version}/synq-recon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "caafd03042c4704b2d8e7cbcf7ae034957840c25833428bda55f0e26c6ec607e"
      url "https://github.com/getsynq/synq-recon/releases/download/v#{version}/synq-recon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "synq-recon"
  desc "Compare a dataset in one database against another, without moving row data"
  homepage "https://docs.synq.io/reconciliation/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synq-recon"
  bash_completion "completions/synq-recon.bash"
  zsh_completion "completions/_synq-recon"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/synq-recon"]
    end
  end
end