# This file was generated by dev-helpers/publish-homebrew-cask.sh. DO NOT EDIT.
cask "synq-recon" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "2df095134b6e6bb8be386b0a039a7236e8d6360a6581334d11eda1040ffac7c9"
      url "https://github.com/getsynq/synq-recon/releases/download/v#{version}/synq-recon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ca0f1f25e5539a3a27bc148de1eeec6ba2984b80bce57456e4ae4ff168de08a5"
      url "https://github.com/getsynq/synq-recon/releases/download/v#{version}/synq-recon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "19eb55202c6a42f7833585300a90c32da1c05458d2a49fa0ea17e98381cad034"
      url "https://github.com/getsynq/synq-recon/releases/download/v#{version}/synq-recon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f4d2af867dfda7e55186709baf13e2b4974d04dfce18d32bc434c3e300b8e51"
      url "https://github.com/getsynq/synq-recon/releases/download/v#{version}/synq-recon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "synq-recon"
  desc "Compare a dataset in one database against another, without moving row data"
  homepage "https://docs.synq.io/reconciliation/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synq-recon"
  bash_completion "completions/synq-recon.bash"
  zsh_completion "completions/_synq-recon"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/synq-recon"]
    end
  end
end