# This file was generated by GoReleaser. DO NOT EDIT.
cask "synqcli" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "0a2327d54b77d9cd7a08408ce184c24e86a10c2ac332e529c2fa997c3a2b7e2b"
      url "https://github.com/getsynq/synqcli/releases/download/v#{version}/synqcli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6806eef7a2825b4148ea0801ef14287cce34cb6bddc62c9f84468eaaa079f6a3"
      url "https://github.com/getsynq/synqcli/releases/download/v#{version}/synqcli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d0af9c4cb0a99dfddb42acc622bf03699fc97582a3ac58853e0d004c04333faa"
      url "https://github.com/getsynq/synqcli/releases/download/v#{version}/synqcli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "77394fb0d878be66090280e0ff1a4da15d64f6d894e3c33976c63bb1a1b01c6d"
      url "https://github.com/getsynq/synqcli/releases/download/v#{version}/synqcli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "synqcli"
  desc "Declare Coalesce Quality monitors, SQL tests and deployment rules as code"
  homepage "https://docs.synq.io/monitors/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synqcli"
  bash_completion "completions/synqcli.bash"
  zsh_completion "completions/_synqcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/synqcli"]
    end
  end

  # No zap stanza required
end
