# This file was generated by GoReleaser. DO NOT EDIT.
cask "synq-scout" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "f1258f67374a49063b7e61464ed7c8d33fc69496f2675d22dd9382fd6b1b2ab9"
      url "https://github.com/getsynq/synq-scout/releases/download/v#{version}/synq-scout_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a764da8447a13017016c82c00b610062807a73c3741d9b8e2475ebe0b6ed5268"
      url "https://github.com/getsynq/synq-scout/releases/download/v#{version}/synq-scout_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4786ca2421f6813c72a7e1e859154e5b68da92b52fd16b482b5768997f39aaf6"
      url "https://github.com/getsynq/synq-scout/releases/download/v#{version}/synq-scout_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d97bead5f0cabb7cc77649aa3eacdd5ea760f1b060be96aea6c1d5b1ff96173d"
      url "https://github.com/getsynq/synq-scout/releases/download/v#{version}/synq-scout_#{version}_linux_arm64.tar.gz"
    end
  end

  name "synq-scout"
  desc "Run the Coalesce Quality Scout agent, or serve its tools over MCP"
  homepage "https://docs.synq.io/scout/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synq-scout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/synq-scout"]
    end
  end

  # No zap stanza required

end
