# This file was generated by GoReleaser. DO NOT EDIT.
cask "synq-scout" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "88fae2d46b5057a524ca9c72c0873c67264676916907e2b5a51f9240f2d7c440"
      url "https://github.com/getsynq/synq-scout/releases/download/v#{version}/synq-scout_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0ed8c63556d15a96d52dd032e122a2571f03a694c3da521285afc9e83c3419e4"
      url "https://github.com/getsynq/synq-scout/releases/download/v#{version}/synq-scout_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c5fcb115bc641c3ea728cca4264c35e0a2b23b1905549f8ff81a15a618cb24b1"
      url "https://github.com/getsynq/synq-scout/releases/download/v#{version}/synq-scout_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "628f445b9c8438cb68e5db27ce6efecb79cee868321fdebe0c2d66dbacf57aeb"
      url "https://github.com/getsynq/synq-scout/releases/download/v#{version}/synq-scout_#{version}_linux_amd64.tar.gz"
    end
  end

  name "synq-scout"
  desc "Run the Coalesce Quality Scout agent, or serve its tools over MCP"
  homepage "https://docs.synq.io/scout/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synq-scout"
  bash_completion "completions/synq-scout.bash"
  zsh_completion "completions/_synq-scout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/synq-scout"]
    end
  end

  # No zap stanza required
end
