# This file was generated by GoReleaser. DO NOT EDIT.
cask "synq-scout" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "379adbb5ea0c1e7eca152a25d3f619f5d4ddb9a224c591aee02e57cdd1032c79"
      url "https://github.com/getsynq/synq-scout/releases/download/v#{version}/synq-scout_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "13dd3c041ecbed984acef9b7bfe429d5450008c880773211390a374979e5bf81"
      url "https://github.com/getsynq/synq-scout/releases/download/v#{version}/synq-scout_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1fbcfcba7def9380955fcc8a18b2488e0b86461967be1cd02243502f295df79f"
      url "https://github.com/getsynq/synq-scout/releases/download/v#{version}/synq-scout_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bb73f2ffa7c0af69c298392b310dcf140d40323a5e9e5503431dc93fb834d1c4"
      url "https://github.com/getsynq/synq-scout/releases/download/v#{version}/synq-scout_#{version}_linux_amd64.tar.gz"
    end
  end

  name "synq-scout"
  desc "Run the Coalesce Quality Scout agent, or serve its tools over MCP"
  homepage "https://docs.synq.io/scout/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synq-scout"
  bash_completion "completions/synq-scout.bash"
  zsh_completion "completions/_synq-scout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/synq-scout"]
    end
  end

  # No zap stanza required
end
