# This file was generated by dev-helpers/publish-homebrew-cask.sh. DO NOT EDIT.
cask "synq-recon" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "26d338cd8abd109f30c0b5f881c402b8d069c3f141f5929ab7d1c881eccad1df"
      url "https://github.com/getsynq/synq-recon/releases/download/v#{version}/synq-recon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "46d4d41da6b1ba5c09373b25cef2071f608c70ab628ea391284d78022bf5d39d"
      url "https://github.com/getsynq/synq-recon/releases/download/v#{version}/synq-recon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "55c95ac49809faa9241f3eb009ef51d18bfa3c5afd01867259850647de5314e0"
      url "https://github.com/getsynq/synq-recon/releases/download/v#{version}/synq-recon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "db7f02a2f0ad2a30d4ff09f3ce1c060e63c54aa2fe1cab29f629993f688d07dd"
      url "https://github.com/getsynq/synq-recon/releases/download/v#{version}/synq-recon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "synq-recon"
  desc "Compare a dataset in one database against another, without moving row data"
  homepage "https://docs.synq.io/reconciliation/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synq-recon"
  bash_completion "completions/synq-recon.bash"
  zsh_completion "completions/_synq-recon"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/synq-recon"]
    end
  end
end